stages:
  - build
  - test

variables:
  MAVEN_CLI_OPTS: |
    --batch-mode 
    -s .m2/settings.xml
    -Dmaven.repo.local=.m2/repository 
    -Dmaven.repo.remote=$MAVEN_REPO_URL$MAVEN_REPO_ALL_PATH 
    -Drepo.login=$MAVEN_REPO_USER 
    -Drepo.pwd=$MAVEN_REPO_PASSWORD 
    -DaltDeploymentRepository=artifactory::default::$MAVEN_REPO_URL$MAVEN_REPO_PATH
  MAVEN_OPTS: "-Xmx2048m -XX:MaxMetaspaceSize=2048m"

cache:
  key: repository-m2
  paths:
    - .m2/repository/[a-q]*
    - .m2/repository/[r-z]*

maven-build:
  stage: build
  tags:
    - build
  rules:
    - if: $CI_COMMIT_BRANCH == 'main'
    - if: $CI_COMMIT_BRANCH =~ '/release/.+/'
    - if: $CI_COMMIT_TAG =~ /^([0-9]+)\.([0-9]+)\.([0-9]+)(?:-([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?(?:\+[0-9A-Za-z-]+)?$/
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  script:
    - |
      if [ "${CI_COMMIT_REF_NAME}" = "main" ]; then
          VERSION="main-SNAPSHOT"
        elif [ "${CI_COMMIT_REF_NAME}" = "develop" ]; then
          VERSION="develop-SNAPSHOT"
        elif [ -n "${CI_COMMIT_TAG}" ];then
          NOSLASH=$(echo "${CI_COMMIT_TAG}" | tr -s / - )
          VERSION="${NOSLASH}"
        else \
          NOSLASH=$(echo "${CI_COMMIT_REF_NAME}" | tr -s / - )
          VERSION="${NOSLASH}-SNAPSHOT"
        fi
    - echo "Version=${VERSION}"
    - mvn $MAVEN_CLI_OPTS clean install -DskipTests

junit_mock:
  stage: test
  tags:
    - build
  rules:
    - if: $CI_COMMIT_BRANCH == 'main'
    - if: $CI_COMMIT_BRANCH =~ '/release/.+/'
    - if: $CI_COMMIT_TAG =~ /^([0-9]+)\.([0-9]+)\.([0-9]+)(?:-([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?(?:\+[0-9A-Za-z-]+)?$/
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  script:
    - echo "Version=${VERSION}"
    - mvn $MAVEN_CLI_OPTS test

test_integration:
  stage: test
  tags:
    - docker-test
  services:
    - name: docker:24.0.6-dind
  variables:
    DOCKER_HOST: "tcp://docker:2375"
    DOCKER_TLS_CERTDIR: ""
    DOCKER_DRIVER: overlay2
  rules:
    - if: $CI_COMMIT_BRANCH == 'main'
    - if: $CI_COMMIT_BRANCH =~ '/release/.+/'
    - if: $CI_COMMIT_TAG =~ /^([0-9]+)\.([0-9]+)\.([0-9]+)(?:-([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?(?:\+[0-9A-Za-z-]+)?$/
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  script:
    - echo "Version=${VERSION}"
    - mvn $MAVEN_CLI_OPTS verify -DskipUnitTests
  when: manual